import { paarch } from "../assets"
import ProductsGrid from "../components/ProductsGrid"
import { bmsproducts, paproducts } from "../products"
import video from "../assets/O-RAN-LoadCore-Screen-Pop.mp4"

const ChillerPlantManagement = () => {
  return (
    <main className="bg-b-100 pb-10">
      <Header />
      <Intro />
      <article className=' max-lg:hidden flex flex-col items-center my-16 p-10'>
                <h1 className='relative text-g-600 font-semibold text-3xl max-xl:text-3xl mb-4'>INGENIUM - CPM</h1>
                <div className='relative flex justify-center'>
                    <img src={paarch} className='rounded-3xl z-10 border-4 border-b-800 ' alt='PA Architecture'/>
                    <div className='absolute w-full h-full top-[30px] left-[30px] bg-b-800 rounded-3xl' aria-hidden="true"/>
                </div> 
      </article>
      <EMSContent />
      <ProductsGrid productlist={bmsproducts.concat(paproducts)} />
    </main>
  )
}

const Header = () => {
    return (
        <section id="header" className='relative z-10 left-0 top-0 w-full h-[300px] xl:h-[460px] flex items-center lg:mb-10 border-b-[20px] border-b-800 rounded-bl-3xl rounded-br-3xl overflow-clip' style={{backgroundImage:"url(https://waterchillers.com/wp-content/uploads/2023/09/chiller_efficiency.jpg)", backgroundSize: "cover", backgroundPosition: "100% 50%"}}>
            <h1 className='absolute bottom-16 left-[5%] lg:left-[10%] text-4xl xl:text-6xl font-bold text-white z-20'> Chiller Plant <br/> Management</h1>
            <div className="h-full w-full bg-black/30" aria-hidden="true" />
        </section>
    )
}
  
  
const Intro = () => {
    return (
        <article className="flex flex-col md:flex-row justify-center my-10 py-10 xl:w-3/4 mx-auto">
            <h1 className="md:w-2/5 mx-10 my-5 font-semibold text-b-900 text-2xl xl:text-4xl md:text-right">CHILLER PLANT <br className="block" />MANAGEMENT <span className="text-black max-lg:hidden"> (CPM)</span></h1>
            <div className="w-[4px] bg-black" aria-hidden="true" />
            <p className="md:w-3/5 mx-10 flex items-center xl:text-[17px]">We also provide Chiller Plant Management Solutions for your Management Systems, aiding in effectively reducing the significant amounts of heat that can be generated by the systems in place, greatly improving it's efficiency.</p>
        </article>
    )
}

const EMSContent = () => {
    return (
        <section className="max-xl:hidden relative flex items-center h-[600px] mx-auto my-5 py-20 2xl:text-[20px] font-medium">     
            <div className="z-50 w-1/2 left-1/4 p-5">
                <h1 className="text-center text-2xl xl:text-4xl font-bold text-b-950 my-10">Energy Management System</h1>
                <p className="mx-auto my-5">Keysight Data Logger (formerly Agilent Data Logger) Interface for Greenmark Certification</p>
                <p className="mx-auto my-5">Ingenium Automation has developed the following interfaces for Keysight Data Loggers. Our data logger interface enables accurate data transfer between chiller plant rooms and Building/Facility management system to optimize the energy consumed in the chiller plant rooms.</p>
                <p className="mx-auto my-5">Keysight data loggers are highly accurate in chiller plant temperature and flow meter readings. One of the widely adopted products worldwide for BCA Green Mark certifications.</p>
                <ul className="mx-auto my-5">Types of Interfaces:
                    <li className="list-disc mx-10">OPC Server Interface for Keysight Data Logger.</li>
                    <li className="list-disc mx-10">Bacnet IP Interface for Keysight Data Logger. </li>
                </ul>
                <p className="mx-auto my-5">With our product numerous customers have achieved Platinum and Gold certifications.</p>
            </div>
            <video className="w-1/2" controls >
                <source src={video} type="video/mp4"/>
            </video>
        </section>
    )
}

export default ChillerPlantManagement
