//building automation and control
//building management systems
export const bmsproducts = [
    {
        id: "0",
        name: "SpaceLogic™ AS-P Automation Server",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=106275233_AS-P_Controller_web&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Core of the Management System",
        link: "https://www.se.com/us/en/product-range/106275233-spacelogic-asp-automation-server/?parent-subcategory-id=104130294&filter=business-2-building-automation-and-control",
    },
    {
        id: "1",
        name: "SpaceLogic™ AS-B Automation Server",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=106276574_AS-B_AutoServer_web&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Core of the Management System",
        link: "https://www.se.com/us/en/product-range/106276574-spacelogic-asb-automation-server/?parent-subcategory-id=104130294&filter=business-2-building-automation-and-control",
    },
    {
        id: "2",
        name: "Room Purpose Controller",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=range-66378&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "IP-enabled BACnet room controller",
        link: "https://www.se.com/us/en/product-range/66378-connected-room-solution/?parent-subcategory-id=104130293&filter=business-2-building-automation-and-control",
    },
    {
        id: "3",
        name: "Multipurpose Controller",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=MP-C-24A-M_EasyLogic&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",    
        desc: "Multi-purpose BACnet MS/TP based field controller for plantroom",
        link: "https://www.se.com/us/en/product-range/203404101-easylogic-mpc-controller/",
    },
    {
        id: "4",
        name: "IP-IO Modules",
        img: "https://ecostruxure-building-help.se.com/graphics/en-US/graphics255400.png",
        desc: "I/O expansion to your HVAC application ",
        link: "https://www.se.com/us/en/product-range/106275687-spacelogic-ipio-expansion-module/?parent-subcategory-id=104130291&filter=business-2-building-automation-and-control",
    },
    {
        id: "5",
        name: "Building Operation Software",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=EcoStruxure-Building-Operation&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "A single solution for your complex needs",
        link: "https://www.se.com/us/en/product-range/62111-ecostruxure-building-operation-software/",
    },
    {
        id: "6",
        name: "EcoStruxure™ Building Advisor",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=EcoStruxure-Building-Advisor&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Building management services with HVAC analytics",
        link: "https://www.se.com/us/en/product-range/39297330-ecostruxure-building-advisor/#overview",
    },
]

//human machine interfaces
export const hmiproducts = [
    {
        id: "0",
        name:"Harmony ST6",
        img:"https://download.schneider-electric.com/files?p_Doc_Ref=ST6_RP20220615&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc:"High-resolution and cost-efficient basic HMI",
        link:"https://www.se.com/us/en/product-range/65770-harmony-st6/",
    },
    {
        id: "1",
        name:"Magelis STO, STU",
        img:"https://download.schneider-electric.com/files?p_Doc_Ref=STU-STO_5774_RPODA18001&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc:"High-resolution and cost-efficient basic HMI",
        link:"https://www.se.com/us/en/product-range/5774-harmony-sto-stu/",
    },
    {
        id: "2",
        name:"Easy Harmony GXU",
        img:"https://download.schneider-electric.com/files?p_Doc_Ref=main+image_63028&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc:"Essential panels, touch screen",
        link:"https://www.se.com/in/en/product-range/63028-easy-harmony-gxu/",
    },
    {
        id: "3",
        name:"Magelis GTU",
        img:"https://download.schneider-electric.com/files?p_Doc_Ref=GTU_61981_RPMFS17001&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc:"Designed to fill your specific HMI application needs",
        link:"https://www.se.com/us/en/product-range/61981-magelis-gtu/",
    },
    {
        id: "4",
        name:"EcoStruxure™ Secure Connect Advisor",
        img:"https://download.schneider-electric.com/files?p_Doc_Ref=VIJEO_RP19047&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc:"Your secure remote access solution",
        link:"https://www.se.com/us/en/product-range/63815-ecostruxure-secure-connect-advisor/",
    },
    {
        id: "5",
        name:"EcoStruxure™ Operator Terminal Expert",
        img:"https://download.schneider-electric.com/files?p_Doc_Ref=VIJEO_1054_RPSCT17001&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc:"Touchscreen configuration s/w with UI design and gestures",
        link:"https://www.se.com/us/en/product-range/62621-ecostruxure-operator-terminal-expert/",
    },
    {
        id: "6",
        name:"EcoStruxure™ Machine SCADA Expert",
        img:"https://download.schneider-electric.com/files?p_Doc_Ref=main_63734&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc:"Lite SCADA for line management",
        link:"https://www.se.com/us/en/product-range/63734-ecostruxure-machine-scada-expert/",
    },
    {
        id: "7",
        name:"Vijeo Designer",
        img:"https://download.schneider-electric.com/files?p_Doc_Ref=1054_main&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc:"HMI configuration Software",
        link:"https://www.se.com/us/en/product-range/1054-vijeo-designer/",
    },
]

//power management systems
export const pmsproducts = [
    {
        id: "0",
        name: "EcoStruxure™ Power Advisor",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=EcoStruxure-Power-Advisor&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Analytics for power management and distribution system",
        link: "https://www.se.com/in/en/product-range/65478-ecostruxure-power-advisor/#overview",
    },
    {
        id: "1",
        name: "EcoStruxure™ Power Monitoring Expert",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=EcoStruxure_PME_Range&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Energy supply management software for large sites",
        link: "https://www.se.com/in/en/product-range/65404-ecostruxure-power-monitoring-expert/#overview",
    },
    {
        id: "2",
        name: "PowerLogic™ PowerTag",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=PB120401&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Wireless energy sensor",
        link: "https://www.se.com/in/en/product-range/63626-powerlogic-powertag/",
    },
    {
        id: "3",
        name: "PowerLogic™ PM5000 series",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=RDS_61281_PM5000_series&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "High-end cost management capabilities in an affordable power meter",
        link: "https://www.se.com/hk/en/product-range/61281-powerlogic-pm5000-series/",
    },
    {
        id: "4",
        name: "PowerLogic™ ION9000",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=ION9000_web_only&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Advanced power quality meets unparalleled innovation",
        link: "https://www.se.com/in/en/product-range/64241-powerlogic-ion9000/",
    },
    {
        id: "5",
        name: "PowerLogic™ ION8650 Power Quality Meters",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=61053_main&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Revenue and power quality power meters",
        link: "https://www.se.com/in/en/product-range/61053-powerlogic-ion8650-power-quality-meters/",
    },
    {
        id: "6",
        name: "Digital AMP / VLT / FRE",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=RDS-994_%28web-only%29&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "DIN-rail mounted ammeter - voltmeter - frequencemeter",
        link: "https://www.se.com/in/en/product-range/994-digital-amp-vlt-fre/",
    },
    {
        id: "7",
        name: "PM2000 series",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=63370_image-of-range&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "EasyLogic Power & Energy meter POP/RS,IO",
        link: "https://www.se.com/us/en/product-range/63370-pm2000-series/",
    },
]

//data center infrastructure management
export const dcimproducts = [
    {
        id: "0",
        name: "EcoStruxure™ IT Expert",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=ECOIT_ITEXPERT_3_RANGE_H&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "The industry's first cloud-based DCIM solution",
        link: "https://www.se.com/us/en/product-range/65972-ecostruxure-it-expert/#overview",
    },
    {
        id: "1",
        name: "EcoStruxure™ IT Data Center Expert",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=ESXIT_DCE_RANGE_H&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Centralized data center infrastructure management",
        link: "https://www.se.com/us/en/product-range/61851-ecostruxure-it-data-center-expert/#overview",
    },
    {
        id: "2",
        name: "UPS Network Management Cards",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=ECOIT_IT_NMC3_LIC_RANGE_H&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Network enable your APC UPS to enhance manageability",
        link: "https://www.se.com/us/en/product-range/61936-ups-network-management-cards/?parent-category-id=88438&parent-subcategory-id=7820&filter=business-3-critical-power-cooling-and-racks",
    },
    {
        id: "3",
        name: "EcoStruxure™ IT SmartConnect",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=SPD_SmartConnect_Range_F_H&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Remote UPS power monitoring for APC Smart-UPS",
        link: "https://www.se.com/us/en/product-range/64112341-ecostruxure-it-smartconnect/?parent-category-id=88438&parent-subcategory-id=7820&filter=business-3-critical-power-cooling-and-racks",
    },
    {
        id: "4",
        name: "Environmental and security - NetBotz",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=ESXIT_NETBOTZ_RANGE_H&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "NetBotz is a flexible environmental monitoring, surveillance and physical security solution",
        link: "https://www.se.com/us/en/product-range/61830-netbotz/",
    },
    {
        id: "5",
        name: "EcoStruxure™ IT Advisor",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=ESXIT_ITA_RANGE_H&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "A cloud-based asset and planning software",
        link: "https://www.se.com/us/en/product-range/66103-ecostruxure-it-advisor/#overview",
    },
]

//safety and security
//fire products
export const fireproducts = [
    {
        id: "0",
        name: "Esmi Fire Detection Panels UL",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=Esmi_Ultima_Fire_alarm_Panel&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Flexible, analogue addressable UL 864 approved fire alarm panels",
        link: "https://www.se.com/in/en/product-range/66361-esmi-fire-detection-panels-ul/?parent-subcategory-id=86785",
    },
    {
        id: "1",
        name: "Esmi Conventional Components",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=Esmi_range_photo_conven_UL&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Conventional detection products and components",
        link: "https://www.se.com/in/en/product-range/66363-esmi-conventional-components-ul/?parent-subcategory-id=86785",
    },
    {
        id: "2",
        name: "Esmi Addressable Components",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=Esmi_Addressable_range_photo&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "High quality addressable detection components for all needs",
        link: "https://www.se.com/in/en/product-range/66362-esmi-addressable-components-for-ultima-range-ul/?parent-subcategory-id=86785",
    },
    {
        id: "3",
        name: "Esmi Fire Detection Panels EN 54",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=Esmi_fire_detection_panels_vs1&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Modular, user-friendly fire detection panels",
        link: "https://www.se.com/in/en/product-range/63651-esmi-fire-detection-panels-en-54/?parent-subcategory-id=86785",
    },
    {
        id: "4",
        name: "Esmi Addressable Components EN 54",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=Esmi_addressable_components_for_alc_range&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "High quality detection products and components for all needs",
        link: "https://www.se.com/in/en/product-range/63652-esmi-addressable-components-for-alc-range-en-54/?parent-subcategory-id=86785",
    },
    {
        id: "5",
        name: "Esmi Conventional Components EN 54",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=Esmi_conventional_components&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "High quality conventional detection products",
        link: "https://www.se.com/in/en/product-range/63654-esmi-conventional-components-en-54/?parent-subcategory-id=86785#overview",
    },
    {
        id: "6",
        name: "Esmi Fire Software",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=Ecostruxure_Fire_Expert&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Online application for Esmi fire detection systems",
        link: "https://www.se.com/in/en/product-range/63656-esmi-fire-software-and-online-applications/?parent-subcategory-id=86785#overview",
    },
]

//safety products
export const safetyproducts = [
    {
        id: "0",
        name: "Security Expert Security Purpose Controller",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=ProductImage_SP-C&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/in/en/product/SP-C/controller-ecostruxure-security-expert-security-purpose-controller/",
    },
    {
        id: "1",
        name: "Security Expert Security Purpose Power Module",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=productimage_SP-PSU-4A&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/au/en/product/SP-PSU-4A/security-expert-security-purpose-power-module-4-a/",
    },
    {
        id: "2",
        name: "Security Expert Security Purpose Door Expansion",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=productimage_SP-RDM2&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/in/en/product/SP-RDM2/security-expert-security-purpose-door-expansion-module/",
    },
    {
        id: "3",
        name: "Security Expert Security Purpose Door Mini Expansion",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=Security_Expert_2Dr_Mini_Expan&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/au/en/product/SP-MRDM2/security-expert-2-door-mini-expander/",
    },
    {
        id: "4",
        name: "Security Expert Security Purpose IO Expansion",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=productimage_SP-IO84&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/au/en/product/SP-IO84/security-expert-security-purpose-input-output-expansion-module/",
    },
    {
        id: "5",
        name: "Security Expert Door Control Unit",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=Security_Expert_Dr_Cont_Unit&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png", 
        desc: "",
        link: "https://www.se.com/au/en/product/SP-DCU/security-expert-door-control-unit/",
    },
    {
        id: "6",
        name: "Security Expert Smartcard Readers",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=productimage_SX-DRD-SB_SX-RD-S&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/au/en/product/SX-RD-SB/security-expert-smartcard-reader-13-56mhz-mullion-black/",
    },
    {
        id: "7",
        name: "Security Expert Wall Plate Smartcard Readers",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=Wallplate_Reader-Black_Keypad&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/au/en/product/SX-DRK-XB-BT/security-expert-smartcard-reader-13-56mhz-125khz-pin-and-keypad-wall-plate-bluetooth/",
    },
    {
        id: "8",
        name: "Security Expert Mini Smartcard Readers",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=Mini_reader-black&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/us/en/product/SX-DRD-MB-BT/security-expert-smartcard-reader-125-khz-13-56mhz-mini-black-bluetooth/",
    },
    {
        id: "9",
        name: "Security Expert Key Tag",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=ProductImage_SX-TAG&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/au/en/product/SX-TAG-MF-HID/security-expert-key-tag-mifare-13-56mhz-125khz-hid-black/",
    },
    {
        id: "10",
        name: "Security Expert Signo Wall Readers",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=SIGNO_40&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/fr/fr/product/40NKS0000038ESE01/hid-signo-40-wall-rdr-pigtail-std-prof-csi-format-multi-tech/",
    },
    {
        id: "11",
        name: "LCD Keypads",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=productimage_SX-KLCS-B&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/au/en/product/SX-KLCS-B/security-expert-touch-sense-lcd-keypad-black/",
    },
    {
        id: "12",
        name: "Intercoms",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=Security_Expert_VoIP_INT-w-Cam&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/in/en/product/SX-IPI-C/security-expert-ip-intercom-with-camera-12vdc-350ma-5c55c-ip54-voip/",
    },
    {
        id: "13",
        name: "Din Rail Enclosures",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=ProductImage_EN-DIN-24&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/sa/en/product/EN-DIN-24/security-expert-enclosure-din-2x4-wallmount/",
    },
    {
        id: "14",
        name: "Security Expert Mobile App",
        img: "https://play-lh.googleusercontent.com/QVXFV70FeH2IKkxVs_LzqofWKpoHkLWhR0TNrtDHJCDWBj0ZlsuiB5pLwWiMvZ9Xug=w240-h480-rw",
        desc: "",
        link: "https://www.se.com/in/en/product-range/65214-ecostruxure-security-expert/",
    },
]

//cctv products
export const cctvproducts = [
    {
        id: "0",
        name: "DS 2CD1313G0E I",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/603/8cc/5be/6038cc5bef457197437179.png",
        desc: "1.3 MP IR Fixed Network Turret Camera",
        link: "https://www.hikvisionindia.com/product-detail/ds-2cd1313g0e-i",
    },
    {
        id: "1",
        name: "DS 2CD1723G1 I(Z)(S)",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/603/8cd/828/6038cd828db67647338527.jpg",
        desc: "2.0 MP VF Network Dome Camera",
        link: "https://www.hikvisionindia.com/product-detail/ds-2cd1723g1-izs",
    },
    {
        id: "2",
        name: "DS 2DB4223I CX (WE/316L)(B)",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/603/8cd/677/6038cd677e7b1371590289.png",
        desc: "2 MP 23× Explosion Proof IR Zoom Bullet Camera",
        link: "https://www.hikvisionindia.com/product-detail/ds-2db4223i-cx-we316lb",
    },
    {
        id: "3",
        name: "DS-1331HZ-IRC",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/603/c7b/b52/603c7bb52d1aa924374700.jpg",
        desc: "Outdoor Housing",
        link: "https://www.hikvisionindia.com/product-detail/ds-1331hz-irc",
    },
    {
        id: "4",
        name: "DS-2AE4225TI-D",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/603/c7c/e50/603c7ce50132e136645695.png",
        desc: "2 MP IR Turbo 4-Inch Speed Dome",
        link: "https://www.hikvisionindia.com/product-detail/ds-2ae4225ti-d",
    },
    {
        id: "5",
        name: "DS-2CC1172P(N)-IR1T(IR3T)(IR5T)",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/604/899/b89/604899b893889298568278.jpg",
        desc: "540 TVL CCD IR Weather-proof Bullet Camera",
        link: "https://www.hikvisionindia.com/product-detail/ds-2cc1172pn-ir1tir3tir5t",
    },
    {
        id: "6",
        name: "DS-2CC11A2P-VFIR3",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/604/8a1/c1a/6048a1c1a70cf714500731.jpg",
        desc: "700 TVL Vari-focal IR Bullet Camera",
        link: "https://www.hikvisionindia.com/product-detail/ds-2cc11a2p-vfir3",
    },
    {
        id: "7",
        name: "DS-2CC1281P(N)-AVFIR3",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/604/8a2/5f2/6048a25f2469d058189445.jpg",
        desc: "600 TVL Vari-focal IR Bullet Camera",
        link: "https://www.hikvisionindia.com/product-detail/ds-2cc1281pn-avfir3",
    },
    {
        id: "8",
        name: "DS-2CC12A2P(N)-IT5",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/604/8a7/ff8/6048a7ff880af807265052.jpg",
        desc: "700 TVL Outdoor EXIR Bullet Camera",
        link: "https://www.hikvisionindia.com/product-detail/ds-2cc12a2pn-it5",
    },
    {
        id: "9",
        name: "DS-2DE7232IW-AE (C)",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/603/a0c/83d/603a0c83de12e136912575.png",
        desc: "2 MP 32 × IR Network Speed Dome Hikvision",
        link: "https://www.hikvisionindia.com/product-detail/ds-2de7232iw-ae-c",
    },
]

//access control products
export const acproducts = [
    {
        id: "0",
        name: "DS-K1101M",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/603/c79/be9/603c79be9424e362457776.jpg",
        desc: "Mifare Card Reader",
        link: "https://www.hikvisionindia.com/product-detail/ds-k1101m",
    },
    {
        id: "1",
        name: "DS-K1102 EK",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/603/c79/0fb/603c790fba4d6492064657.jpg",
        desc: "EM card reader (with a keypad)",
        link: "https://www.hikvisionindia.com/product-detail/ds-k1102-ek",
    },
    {
        id: "2",
        name: "DS-K1104MK",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/604/1dd/6aa/6041dd6aad818369948143.png",
        desc: "Mifare Card Reader with Keyboard",
        link: "https://www.hikvisionindia.com/product-detail/ds-k1104mk",
    },
    {
        id: "3",
        name: "DS-K1801M",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/604/1de/23b/6041de23bd519179121553.jpg",
        desc: "Inductive Card Reader",
        link: "https://www.hikvisionindia.com/product-detail/ds-k1801m",
    },
    {
        id: "4",
        name: "DS-K1A801EF",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/604/1eb/8a1/6041eb8a1d39b000760445.jpg",
        desc: "Fingerprint Time Attendance Terminal",
        link: "https://www.hikvisionindia.com/product-detail/ds-k1a801ef",
    },
    {
        id: "5",
        name: "DS-K1F800-F",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/604/1ec/242/6041ec2424822491739723.jpg",
        desc: "Fingerprint Card Issuer",
        link: "https://www.hikvisionindia.com/product-detail/ds-k1f800-f",
    },
    {
        id: "6",
        name: "DS-K1T105E",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/604/1ec/8b0/6041ec8b09e6a952151529.gif",
        desc: "Standalone Access Control Terminal(em card)",
        link: "https://www.hikvisionindia.com/product-detail/ds-k1t105e",
    },
    {
        id: "7",
        name: "DS-K1F100-D8E",
        img: "https://www.hikvisionindia.com/storage/app/uploads/public/604/1ec/06e/6041ec06e6362150168004.jpg",
        desc: "Card Enrollment Station",
        link: "https://www.hikvisionindia.com/product-detail/ds-k1f100-d8e",
    },
]

//industrial automation and control
//process automation products
export const paproducts = [
    {
        id: "0",
        name: "Modicon M580",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=Modicon_M580_range&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Ethernet Programmable Automation & Safety PLC",
        link: "https://www.se.com/in/en/product-range/62098-modicon-m580epa-controller-safety-plc/?parent-subcategory-id=3950&filter=business-1-industrial-automation-and-control",
    },
    {
        id: "1",
        name: "Modicon M340",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=PF100295&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Mid-range PAC industrial process and infrastructure control",
        link: "https://www.se.com/in/en/product-range/1468-modicon-m340/?parent-subcategory-id=3950&filter=business-1-industrial-automation-and-control",
    },
    {
        id: "2",
        name: "Modicon M241",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=62129_main&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Programmable Logic Controller for performance-demanding applications",
        link: "https://www.se.com/in/en/product-range/62129-logic-controller-modicon-m241/?parent-subcategory-id=3910&filter=business-1-industrial-automation-and-control",
    },
    {
        id: "3",
        name: "Modicon M221",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=62128_main&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "Programmable logic controller for hardwired architectures",
        link: "https://www.se.com/in/en/product-range/62128-logic-controller-modicon-m221/",
    },
    {
        id: "4",
        name: "AVEVA™ Plant SCADA",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=1500_main&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "High performance site SCADA software solution, enabling smart manufacturing",
        link: "https://www.se.com/in/en/product-range/1500-aveva-plant-scada/?parent-subcategory-id=271724463&filter=business-1-industrial-automation-and-control#overview",
    },
]

export const fielddevices = [
    {
        id: "0",
        name: "Duct Humidity & Temperature Sensor",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=0069023GP_IOPMAIN_ODA19&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/in/en/product/006902321/shd-series-shd100-model-duct-humidity-temperature-sensor-selectable-outputs-095-rhcontinuum-i-net-vista-xenta-satchwell-compatible/",
    },
    {
        id: "1",
        name: "Schneider Electric SHO100-T",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=Outdoor_Humidity_Sensor-3.22.11&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/ie/en/product/SHO100-T/schneider-electric-sho100t/",
    },
    {
        id: "2",
        name: "Wet Differential Pressure switch",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=SPP920_img&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/in/en/product/004701100/spp920020-wet-differential-pressure-switch-6-20-mbar/",
    },
    {
        id: "3",
        name: "Differential wet Pressure Transmitter",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=ODASENSORS+-+GROUP+31&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/in/en/product/6552048000/spw-differential-wet-pressure-transmitter-0-1-bar/",
    },
    {
        id: "4",
        name: "Differential Air Pressure Transmitter",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=EPD301LCD_Image&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/id/en/product/EPD301LCD/differential-air-pressure-trans-for-the-monitoring-of-air-ducts-filters-and-fans-spd310100-300-500-1000pa/",
    },
    {
        id: "5",
        name: "Differential Pressure Switch",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=ODA004701060&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/uk/en/product/004701060/differential-pressure-switch-250-vac-silver-contacts-3-amp-resistive-2-amp-inductive-spd910300pa/",
    },
    {
        id: "6",
        name: "Temperature sensor",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=ODASENSORS+-+GROUP+14&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/in/en/product/006920121/std-series-temperature-sensor-std300300-duct-5050-%C3%A2c/",
    },
    {
        id: "7",
        name: "Immersion Temperature Sensor",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=006920241_IOPMAIN_ODA19&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/in/en/product/006920241/stp-series-immersion-temperature-sensor-stp300100-0-100-pipe-100-mm-probe-2wire-0100-%C3%A2c/",
    },
    {
        id: "8",
        name: "Water Flow Switch",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=CP_water_flow_switch_image&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/sg/en/product/CP-LI-FL-SW-BSP0/cp-water-flow-switch-dn25dn200bsp/",
    },
    {
        id: "9",
        name: "Flow Meter",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=KDF40F_photo_meter_front&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/in/en/product/KDF40F/kd-series-flow-meter-dn65-flanged-stainless-steel-25-m%C2%B3-h-nominal-flow-meter/",
    },
    {
        id: "10",
        name: "Glass Touch Panels",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=LSSMBU12Nx_IOP&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/il/en/product/LSSMBU12NP/panel-glass-touch-panels-for-hotels-modbus-12-buttons-product-order/",
    },
    {
        id: "11", 
        name: "Keycard Holder Touch Panels",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=LSSMKH03Nx_IOP&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link:"https://www.se.com/sg/en/product/LSSMKH03NS/keycard-holder-glass-touch-panels-for-hotels-modbus-sample-order/",
    },
    {
        id: "12",
        name: "Thermostat Glass Touch Panels",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=LSSMTH08NP_image&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link:"https://www.se.com/hk/en/product/LSSMTH08NP/thermostat-glass-touch-panels-for-hotels-modbus-8-buttons-product-order/",
    },
    {
        id: "13", 
        name: "SmartX Temperature Sensor",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=D_OPTIMUM_3B_LCD_BLACK&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/in/en/product/SXWSATXXXSLB/smartx-temperature-sensor-3-buttons-lcd-setpoint-with-optimum-black-cover/",
    },
    {
        id: "14",
        name: "SpaceLogic Thermostat",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=TC907_FRONT_OFF&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/in/en/product/TC907-3A2L/spacelogic-thermostat-fan-coil-on-off-standalone-touchscreen-2p-3-fan-240v-white/",
    },
    {
        id: "15",
        name: "Thermostat, Spacelogic",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=TC903_FRONT_OFF&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/in/en/product/TC903-3A4DPSA/thermostat-spacelogic-fan-coil-proportional-standalone-lcd-5-button-4p-3-fan-external-sensor-240v-white/",
    },
]

//iot products
export const iotproducts = [
    {
        id: "0",
        name: "Indoor air quality sensors",
        img: "https://ecoxpert.se.com/documents/10807/32657645/CO2_Cover_Color.png/848c2b4a-a6e3-424d-ab25-dc14ffc678cc?t=1528868273000",
        desc: "",
        link: "https://ecoxpert.se.com/products/light-and-room-control/sensor-devices/air-quality-sensors/discover",
    },
    {
        id: "1",
        name: "Desk Sensor",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=EBIOTPCWD_Image_of_Product&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/hk/en/product/EBIOTPCWD/desk-occupancy-sensor-ecostruxure-buildingiot-sensor-solution-wireless/",
    },
    {
        id: "2",
        name: "Room Occupancy Sensor",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=EBIOTPCWR_Image_of_Product&p_File_Type=rendition_113_png&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/th/en/product/EBIOTPCWR/room-occupancy-sensor-ecostruxure-buildingiot-sensor-solution-wireless/",
    },
    {
        id: "3",
        name: "IoT Gateway",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=EBIOTPGW_Image_of_Product&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/uk/en/product/EBIOTPGW/gateway-ecostruxure-buildingiot-sensor-solution-wireless-lte-poe/",
    },
    {
        id: "4",
        name: "IoT Platform",
        img: "https://download.schneider-electric.com/files?p_Doc_Ref=EcoStruxure-Building-Advisor&p_File_Type=rendition_369_jpg&default_image=DefaultProductImage.png",
        desc: "",
        link: "https://www.se.com/us/en/product-range/39297330-ecostruxure-building-advisor/#overview",
    }
]